development:
  adapter: postgresql
  encoding: unicode
  database: podcast_fm_development
  pool: 5
  username: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: podcast_fm_test
  pool: 5
  username: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: podcast_fm_production
  pool: 5
  username: postgres
  host: localhost

